/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Objetos_clases.Locacion_clase;
import conexiones.ProyectoResidencia;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos Barahona
 */
public class Modificar_area extends javax.swing.JInternalFrame {

    /**
     * Creates new form Modificar_area
     */
    public Modificar_area() {
        initComponents();
    MostrarArea();
    }
    
       private void MostrarArea(){
           //this.SOPORTE.removeAllItems();
 try{
 Statement stm = con.createStatement();
 ResultSet rs = stm.executeQuery("select * from locacion");
 
 while(rs.next()){
Locacion_clase c = new Locacion_clase();
c.setId_locacion(rs.getInt("id_locacion"));
c.setNombre_locacion(rs.getString("nombre_locacion"));
      
    this.LOCACION.addItem(c);
 }    
 }catch(Exception e){
     JOptionPane.showMessageDialog(null,"Error en la conexion"+e);
 }
         }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID_AREA = new javax.swing.JTextField();
        LOCACION = new javax.swing.JComboBox<Locacion_clase>();
        AREA = new proyectoresidencia.JCTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Modificar Area");

        LOCACION.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar locacion" }));

        AREA.setPlaceholder("Nombre del Area");

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AREA, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(LOCACION, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LOCACION, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AREA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  if(LOCACION.getSelectedItem().equals("Seleccionar locacion") || ID_AREA.getText().equals("")&& AREA.getText().equals(""))
       {
         JOptionPane.showMessageDialog(null,"Campos vacíos","Aviso",JOptionPane.ERROR_MESSAGE);
       }else{
    /*    String unoCombo =  (String) LOCACION.getSelectedItem(); //CONVIERTE EL JCOMBOBOX A STRING 
       String decomponerCOMBO[] = unoCombo.split("-");
       Integer resultadoCombo = Integer.parseInt(decomponerCOMBO[0]); */ 
 
       try{
    PreparedStatement pst = con.prepareStatement("UPDATE area_empresa SET nombre_area='"+AREA.getText()+"' WHERE id_area='"+ID_AREA.getText()+"'");
            pst.executeUpdate();     
}catch(Exception e){
JOptionPane.showMessageDialog(null,"Error"+e);
}
            try{
    PreparedStatement pst = con.prepareStatement("UPDATE area_empresa SET id_locacion='"+LOCACION.getItemAt(LOCACION.getSelectedIndex()).getId_locacion()+"' WHERE id_area='"+ID_AREA.getText()+"'");
            pst.executeUpdate();      
}catch(Exception e){
JOptionPane.showMessageDialog(null,"Error"+e);
}      
            AREA.setText(null);
            LOCACION.setSelectedIndex(0);
            ID_AREA.setText(null);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static proyectoresidencia.JCTextField AREA;
    public static javax.swing.JTextField ID_AREA;
    public static javax.swing.JComboBox<Locacion_clase> LOCACION;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
ProyectoResidencia cc = new ProyectoResidencia();
Connection con=cc.conexion();
}
